language: python

os:
  - linux
  # osx is not supported yet
  #- osx

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

virtualenv:
  # without this, python 3.5 will not work
  system_site_packages: false

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests
