sudo: required

language: python

matrix:
  include:
    # Ubuntu 12.04.5 LTS
    - os: linux
      python: '2.6'
    #- os: linux
    #  python: '2.7'
    #- os: linux
    #  python: '3.3'
    #- os: linux
    #  python: '3.4'
    #- os: linux
    #  python: '3.5'

    # Ubuntu 14.04.3 LTS
    #- os: linux
    #  dist: trusty
    #  python: '2.6'
    #- os: linux
    #  dist: trusty
    #  python: '2.7'
    #- os: linux
    #  dist: trusty
    #  python: '3.3'
    #- os: linux
    #  dist: trusty
    #  python: '3.4'
    #- os: linux
    #  dist: trusty
    #  python: '3.5'

    # OS X 10.10
    - os: osx                                                                                                                                            
      osx_image: xcode6.4
      language: generic
      env: PYENV_VERSION=2.7.11
      #- os: osx
      #  language: python
      #  env: PYENV_VERSION=3.5.1

    # OS X 10.11 
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: PYENV_VERSION=2.7.11
      #- os: osx
      #  language: python
      #  env: PYENV_VERSION=3.5.1

    # OS X 10.11                                                                                                                                         
    - os: osx
      osx_image: xcode8
      language: generic
      env: PYENV_VERSION=2.7.11
      #- os: osx
      #  language: python
      #  env: PYENV_VERSION=3.5.1

    # OS X 10.11                                                                                                                                         
    - os: osx
      osx_image: xcode8.1
      language: generic
      env: PYENV_VERSION=2.7.11
      #- os: osx
      #  language: python
      #  env: PYENV_VERSION=3.5.1

    # OS X 10.11 
    - os: osx
      osx_image: xcode8.2
      language: generic
      env: PYENV_VERSION=2.7.11
    #- os: osx
    #  osx_image: xcode8.2
    #  language: generic
    #  env: PYENV_VERSION=3.5.1

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

virtualenv:
  # without this, python 3.5 will not work
  system_site_packages: false

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
#script: nosetests
script: sh shell_test.sh
